#!/bin/bash

echo '[$#] Number of arguments:' $#
echo '[$@] Parameters passed:' $@
echo '[$?] Was last command successful:' $? # Answer is 0 which means 'yes'
echo '[$1] First argument:' $1
echo '[$2] Second argument:' $2

# [num1 -eq num2] checks if 1st number is equal to 2nd number
# [num1 -ge num2] checks if 1st number is greater than or equal to 2nd number
# [num1 -gt num2] checks if 1st number is greater than 2nd number
# [num1 -le num2] checks if 1st number is less than or equal to 2nd number
# [num1 -lt num2] checks if 1st number is less than 2nd number
# [num1 -ne num2] checks if 1st number is not equal to 2nd number

if [ $# -ne 2 ]; then
  echo "Not exacly 2 arguments passed"
elif [ $# -eq 2 ]; then
  echo "Exaclty 2 argument passed"
fi

if [ $# -gt 2 ]; then
  echo "More then 2 arguments passed"
fi
