#!/bin/bash
message="$(osascript -e 'Tell application "System Events" to display dialog "enter asd" default answer ""' -e 'text returned of result' 2>/dev/null)"

echo asd
echo $message
#
# if [ $? -ne 0 ]; then
#     # The user pressed Cancel
#     exit 1 # exit with an error status
# elif [ -z "$message" ]; then
#     # The user left the project name blank
#     osascript -e 'Tell application "System Events" to display alert "You must enter a project name; cancelling..." as warning'
#     exit 1 # exit with an error status
# fi
#
# address="amedeo@explab.com"
# subject="this is the sunject"
#
# echo "tell application \"Microsoft Outlook\"
# 	set newMessage to make new outgoing message with properties {subject:"lol"}
# 	make new recipient at amedeo@explab.com with properties {email address:{address:"amedeo@explab.com"}}
#
# 	open newMessage
# end tell" | osascript
#
#
# #make new cc recipient at newMessage with properties {email address:{name:"Name", address:"test@example.com"}}
