#!/usr/bin/env python

import sys
import csv
import json

name = sys.argv[1].split(".")[0]

with open(sys.argv[1], "r") as f:
    reader = csv.DictReader(f)
    data = list(reader)
    row_count = len(data)

print row_count
