#!/usr/bin/env python

import sys
import csv
import json

name = sys.argv[1].split(".")[0]

with open(sys.argv[1], "r") as f:
    reader = csv.DictReader(f)
    rows = list(reader)

with open(str(name) + '.json', 'w') as f:
    json.dump(rows, f)
    print "new file: " + str(name) + ".json saved!"
