#!/usr/bin/env python

import sys
import csv
import json

name = sys.argv[1].split(".")[0]

with open(sys.argv[1]) as f:
    data = json.load(f)

with open(str(name) + '_beauty.json', 'w') as f:
    json.dump(data, f, sort_keys=True, indent=4)
    print "new file: " + str(name) + "_beauty.json saved!"
