#!/usr/bin/env python

import sys
import csv
import json

name = sys.argv[1].split(".")[0]

with open(sys.argv[1]) as f:
    data = json.load(f)

first = json.dumps(data[0], indent=4, sort_keys=True)

print "file: json"
print "length: " + str(len(data))
print "sample: " + str(first) + " ..."
