#!/usr/bin/env python

import argparse
import sys
import os

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('infile')
    parser.add_argument('-s', '--size')
    parser.add_argument('-o', '--origin', default="+0+0")
    args = parser.parse_args()

def resize_by_height():
    file_name, file_extension = os.path.splitext(args.infile)
    outfile = file_name + "_" + args.size + args.origin + file_extension
    command = "convert %s -crop %s%s %s" % (args.infile,args.size,args.origin,outfile)
    os.system(command)
    print("image cropped: " + outfile)

resize_by_height()
