#!/usr/bin/python
import sys
sys.path.append(sys.path[0])
from lib.dataviz import *

description = "Do crazy stuff with csv files"
epilog = '''
examples:
    csv file.csv -json # export pretty json
    csv file.csv -l # print general informations
    csv file.csv -uglyjson # export ugly json
'''
DataViz("csv", description, epilog)
