#!/usr/bin/python
import sys
sys.path.append(sys.path[0])
from lib.dataviz import *

description = "Do crazy stuff with csv files"
epilog ="""examples:
    # export json
        csv infile.csv --json
        csv infile.csv --json -ugly
    # general
        csv file.csv -i # print general info
        csv file.csv -l # print lines number
    # export
        csv infile.csv --csv
        csv infile.csv --csv --filter field1 field2 field3
        csv infile.csv --json
        csv infile.csv --json --filter field1 field2 field3
        csv infile.csv --json --add newfield --filters field1 field2
        csv infile.csv -c field -o # get info from field with occurrence
        csv infile.cs + -c field -a # get info from field with average
        csv infile.csv -c field -oa # get info from field with occurrence and average"""

DataViz("csv", description, epilog)
