#!/usr/bin/env python

from urllib2 import Request, urlopen, URLError
import sys
import json
import math

name = sys.argv[1]

key = "AIzaSyACjZxwJS2CEC5TrNmY1WWbEgEKX-bG3uQ"
url = "https://maps.googleapis.com/maps/api/geocode/json"
api = url + "?address=" + name.replace(" ","+") + "&key=" + key

def getHtml (url):
   request = Request(url)
   error = 'Got an error code'
   try:
       response = urlopen(request)
       _resp = response.read()
       return _resp
   except URLError, e:
       print 'Got an error code:', e
       return '{"status": "error", "results", "none"}'

my_json = json.loads(getHtml(api))

lon = str(my_json['results'][0]['geometry']['location']['lng'])
lat = str(my_json['results'][0]['geometry']['location']['lat'])

northeast = [
  my_json['results'][0]['geometry']['viewport']['northeast']['lng'],
  my_json['results'][0]['geometry']['viewport']['northeast']['lat']]

southwest = [
  my_json['results'][0]['geometry']['viewport']['southwest']['lng'],
  my_json['results'][0]['geometry']['viewport']['southwest']['lat']]

print "{"
print "   \"name\": \"%s\"," % name
print "   \"pos\": [%s, %s]," % (lon,lat)
print "   \"northeast\": %s," % northeast
print "   \"southwest\": %s," % southwest
print "   \"width\": %s," % math.fabs(northeast[0] - southwest[0])
print "   \"heigth\": %s," % math.fabs(northeast[1] - southwest[1])
print "},"

# print str(my_json['results'][0])
