#!/usr/bin/env python
# run with Python 2.7.10

# how to use it
# address_to_gps "123 My Address, Place, Country"
# address_to_gps "1600 Amphitheatre Parkway, Mountain View, CA"

from urllib2 import Request, urlopen, URLError
import sys
import json

name = sys.argv[1]

key = "AIzaSyACjZxwJS2CEC5TrNmY1WWbEgEKX-bG3uQ"
url = "https://maps.googleapis.com/maps/api/geocode/json"
api = url + "?address=" + name.replace(" ","+") + "&key=" + key

def getHtml (url):
   request = Request(url)
   error = 'Got an error code'
   try:
       response = urlopen(request)
       _resp = response.read()
       return _resp
   except URLError, e:
       print 'Got an error code:', e
       return '{"status": "error", "results", "none"}'

my_json = json.loads(getHtml(api))

# print my_json
# print "status: "                    + str(my_json['status'])
# print "formatted_address: "         + str(my_json['results'][0]['formatted_address'])
# print "type: "                      + str(my_json['results'][0]['types'][0])
# print "position: ["                  + str(my_json['results'][0]['geometry']['location']['lng']) + ", " + str(my_json['results'][0]['geometry']['location']['lat']) + "]"

# print json.dumps(my_json['results'], sort_keys=True, indent=2)

lon = str(my_json['results'][0]['geometry']['location']['lng'])
lat = str(my_json['results'][0]['geometry']['location']['lat'])

print "all: %s" % (my_json['results'][0])
print "name: %s" % name
print "pos: [%s, %s]" % (lon,lat)
