#!/usr/bin/env python3

import os
import sys

message = sys.argv[1]
LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

def hackcaesar(text):
    for key in range(len(LETTERS)):
       translated = ''
       for symbol in message:
          if symbol in LETTERS:
             num = LETTERS.find(symbol)
             num = num - key
             if num < 0:
                num = num + len(LETTERS)
             translated = translated + LETTERS[num]
          else:
             translated = translated + symbol
    print('Hacking key #%s: %s' % (key, translated))

print(message)
print(hackcaesar(message))
#check the above function
# text = "CEASER CIPHER DEMO"
# s = 4
#
# print "Plain Text : " + text
# print "Shift pattern : " + str(s)
# print "Cipher: " + encrypt(text,s)


# message = 'GIEWIVrGMTLIVrHIQS' #encrypted message
