#!/usr/bin/python
import urllib2
import re

URL = 'https://hk.stubhubtickets.com/backoffice/cachejs/DatosEventos-1007-30234371.js'
response = urllib2.urlopen(URL)
result = response.read()
print result

# matcher_rex = re.compile(r'^var\s+(?P<varname>\w+)\s+=\s+"(?P<varvalue>[\w\s]+)";?$')
# matches = matcher_rex.match(result)
#
# if matches:
#     name, value = matches.groups()
#     print name, value
